## Mod
mod_name=Berry Pouch
mod_id=berrypouch
mod_author=Flandre,Andromeda,Thirace,kim,YajatKaul
mod_version=0.6.1-beta
mod_description=Berry Pouch
maven_group=com.github.flandre923
license=ARR
enabled_platforms=fabric,neoforge

# Minecraft
minecraft_version=1.21.1

## Dependencies

# Mod Loader/API
architectury_api_version=13.0.8
fabric_loader_version=0.17.2
fabric_api_version=0.116.7+1.21.1
neoforge_version=21.1.217
neoforge_major_version=21
neoforge_loader_version=4

# Cobblemon
kotlin_for_forge_version=5.10.0
kotlin_stdlib_version=2.2.20
cobblemon_version=1.8.0+1.21.1
cobblemon_min_ver=1.8.0
cobblemon_max_ver=1.9.0

# Radical Cobblemon Trainers API (see https://www.curseforge.com/minecraft/mc-mods/radical-cobblemon-trainers-api/files)
rctapi_min_version=0.14.0-beta
rctapi_common_version=7248220
rctapi_fabric_version=7248222
rctapi_neoforge_version=7248221

# Forge Config API Port (see https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files)
fcap_version=21.1.1
fcap_min_ver=21.1.1
fcap_max_ver=

## Dev Dependencies

# Patchouli (see https://www.curseforge.com/minecraft/mc-mods/patchouli/files)
patchouli_version=4966125

# Patchouli Fabric (see https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric/files)
patchouli_fabric_version=4966124

# Cobblepedia (see https://www.curseforge.com/minecraft/mc-mods/cobblepedia/files)
cobblepedia_version=5057902
cobblepedia_fabric_version=5057903

# Configured (see https://www.curseforge.com/minecraft/mc-mods/configured/files)
configured_version=5101367
configured_fabric_version=5180902

# PKGBadges/Cobblebadges (see https://www.curseforge.com/minecraft/mc-mods/pkgbadges)
pkgbadges_version=5441760
pkgbadges_fabric_version=5343582

# SimpleTMs (see https://www.curseforge.com/minecraft/mc-mods/simpletms-tms-and-trs-for-cobblemon)
simpletms_version=5080374
simpletms_fabric_version=5080372

# Accessories (see https://www.curseforge.com/minecraft/mc-mods/accessories)
accessories_version=1.1.0-beta.39+1.21.1
# https://maven.wispforest.io/io/wispforest/owo-lib/
owo_version=0.12.15.4+1.21
owo_neo_version=0.12.15.1-beta.6+1.21

# JEI (see https://www.curseforge.com/minecraft/mc-mods/jei/files)
jei_version=19.21.1.248
jei_mc_version=1.21.1

#
endec_version=0.1.5.1
endec_gson_version=0.1.3.1
endec_netty_version=0.1.2
endec_jankson_version=0.1.3.1

#
ffapi_version=0.116.7+2.2.0+1.21.1
ffloader_version=2.5.29+0.16.0+1.21


## Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
#org.gradle.java.home=/Program Files/Java/jdk-21.0.4+7

modrinth_id=y7TzXi4L
curseforge_id=1246510